import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"; // Adjusted path for globals.css
import 'react-loading-skeleton/dist/skeleton.css';
import TopNavBar from "@/components/navigation/TopNavBar";
import BottomNavBar from "@/components/navigation/BottomNavBar";
import { I18nProviderClient } from '@/i18n/client'; // Import client provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App", // This will likely be internationalized later
  description: "Generated by create next app", // This too
};

export default function RootLayout({
  children,
  params: { locale } // Destructure locale from params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-16`}
      >
        <I18nProviderClient locale={locale}> {/* Wrap with provider */}
          <TopNavBar />
          <main className="flex-grow">
            {children}
          </main>
          <BottomNavBar />
        </I18nProviderClient>
      </body>
    </html>
  );
}
